#! /usr/bin/env bash


script_dir="$(dirname "$(realpath "$0")")"
root_dir="$(realpath "$script_dir/..")"
zig_out_dir="$(realpath "$root_dir/zig-out")"
exe="$(realpath "$zig_out_dir/v10")"

pushd "$zig_out_dir" || exit 1

lldb-zig "$exe"  \
    -o "b v10_platform.GameCode.load" \
    -o "r" \
    -o "fin" \
    -o "c"


popd
