#! /usr/bin/env bash

script_dir="$(dirname "$(realpath "$0")")"
common_script_path="$(realpath "$script_dir/common.py")"
root_dir="$(realpath "$script_dir/..")"
zig_out_dir="$(realpath "$root_dir/zig-out")"
data_dir="$(realpath "$root_dir/data")"
exe="$(realpath "$zig_out_dir/v10")"

pushd "$data_dir" || exit 1


lldb-zig  "$exe"  \
    -o "command script import $common_script_path" \
    -o "script common.register_default_aliases()" \
    -o "script common.initial_launch()" \


popd




